### ISSUE TITLE
Blog Post layout

### ISSUE THREAD

**Issue by hgcl** [robinmetral/clarale.com#46]
Style blog post layout to be similar to Medium.

ex: https://medium.com/@clarale/colors-1-vintage-palettes-for-your-website-3f8bf1ad10d3?source=friends_link&sk=213e9ee3e797ea3246137a91be4c10c0

Adapt:
- [x] Body width
- [x] Content text size
- [x] Headings text size
- [x] Line height
- [x] Space before / after title
- [x] Add a divider (in Medium, it's three dots)

A few other things:
- [x] Line height of main title should be bigger. Letters from second text line shouldn't overlap the first line (https://www.clarale.com/blog/how-to-create-an-infographic-with-illustrator-2-2)
- [x] Do not display feature image in post

**Comment by robinmetral** [comment]
@hgcl Notes:

- Space before/after title: wrap the first element in a paragraph tag and you'll get the margin before that paragraph. Basically evrything should be either a paragraph (with other things inside of it), an image, or a sub-heading.
- Remove the empty paragraph you've used to increase spacing between paragraphs - this should be done in code to avoid the extra markup
- Divider: add a divider from WordPress (the `<hr />` element). Otherwise I can't style it :slightly_smiling_face: 
- Sub-headings: you should use `h2` for secondary headings in your content for better semantics (Medium uses h3 but that's not a good practice). I'll style them however you want!
